version: "1.0"
allowlist:
  # Coreutils (50+ commands)
  - awk
  - basename
  - cat
  - chmod
  - chown
  - cp
  - cut
  - date
  - dd
  - df
  - dirname
  - du
  - echo
  - env
  - expand
  - expr
  - find
  - grep
  - head
  - hostname
  - id
  - kill
  - less
  - ln
  - ls
  - mkdir
  - mktemp
  - mv
  - paste
  - pwd
  - readlink
  - realpath
  - rm
  - rmdir
  - sed
  - seq
  - sleep
  - sort
  - split
  - stat
  - tail
  - tar
  - tee
  - test
  - touch
  - tr
  - true
  - uname
  - uniq
  - wc
  - which
  - whoami
  - xargs

  # Development tools (40+ commands)
  - cargo
  - rustc
  - rustup
  - git
  - gh
  - docker
  - docker-compose
  - kubectl
  - helm
  - terraform
  - ansible
  - make
  - cmake
  - gcc
  - g++
  - clang
  - go
  - python
  - python3
  - pip
  - pip3
  - node
  - npm
  - npx
  - yarn
  - pnpm
  - deno
  - bun
  - ruby
  - gem
  - bundle
  - java
  - javac
  - mvn
  - gradle
  - dotnet
  - php
  - composer
  - perl
  - lua

  # System utilities (30+ commands)
  - systemctl
  - journalctl
  - apt
  - apt-get
  - apt-cache
  - dpkg
  - yum
  - dnf
  - pacman
  - snap
  - flatpak
  - brew
  - ps
  - top
  - htop
  - free
  - uptime
  - lsof
  - netstat
  - ss
  - ip
  - ifconfig
  - ping
  - curl
  - wget
  - ssh
  - scp
  - rsync
  - sudo
  - su

  # Text editors and pagers (10+ commands)
  - vim
  - vi
  - nano
  - emacs
  - less
  - more
  - bat
  - cat

  # File compression (10+ commands)
  - gzip
  - gunzip
  - bzip2
  - bunzip2
  - xz
  - unxz
  - zip
  - unzip
  - 7z
  - tar

  # Search and analysis (10+ commands)
  - rg
  - ag
  - ack
  - fd
  - fzf
  - jq
  - yq
  - xmllint
  - diff
  - patch

  # Version control (5+ commands)
  - git
  - svn
  - hg
  - bzr

  # Additional utilities (10+ commands)
  - tmux
  - screen
  - watch
  - time
  - strace
  - ltrace
  - ldd
  - file
  - strings
  - hexdump

exclude: []

quality:
  min_confidence: 0.60
  min_coverage: 0.20
  allow_low_quality: false

extraction:
  jobs: 4
  installed_only: true
  scan_path: false
